config/routes.rb
Rails.application.routes.draw do

  resources :starships
  
  root 'site#index'
  
  get 'signin', to: 'sessions#new'
  post 'signin', to: 'sessions#create'
  delete 'signout', to: 'sessions#destroy'

  
  resources :users, only: [:new, :create, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/starship.rb
class Starship < ApplicationRecord
end

app/models/user.rb
class User < ActiveRecord::Base

has_secure_password 

validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }

VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    protect_from_forgery with: :exception
    before_action :verified_user
    helper_method :current_user

    private

    def current_user
        User.find_by(id: session[:user_id])
    end

    def user_is_authenticated
        !!current_user
    end

    def verified_user 
        redirect_to '/signin' unless user_is_authenticated
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    skip_before_action :verified_user, only: [:new, :create]

    def new
    end

    def create
        user = User.find_by(email: params[:email])
        if user.try(:authenticate, params[:password])
            session[:user_id] = user.id 
            flash[:success] = "Welcome explorer, You have signed in."
            redirect_to "/"
        else
            flash.now[:danger] = "I am sorry. Our Starfinder AI can not find that login information."
            render "new"
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = "You have signed out. See you soon explorer."
        redirect_to root_path
    end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
 
  skip_before_action :verified_user, only: [:index]
  
  def index
  end

end

app/controllers/starships_controller.rb
class StarshipsController < ApplicationController

    def index
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    skip_before_action :verified_user, only: [:new, :create]
    before_action :set_user, only: [:edit, :update]

    def new
        @user = User.new 
    end

    def create
        @user = User.new(user_params)
        if @user.save 
            flash[:success] = "Welcome to Starfinder 2.0 #{@user.username}"
            session[:user_id] = @user.id 
            redirect_to root_url 
        else
            render "new"
        end
    end

    def edit 
    end

    def update
        if @user.update(user_params)
            flash[:success] = "Your account was updated successfully"
            redirect_to root_url
        else
            render "edit"
        end 
    end

    private 

    def set_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/starships_helper.rb
module StarshipsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<html lang="en">
  <head>
    <title>Starfinder2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <div class="header">
    <div class="image-dice">
        <%= link_to image_tag("/StarDieResized2.jpg", alt: "Starfinder Dice"), root_url%>
        <h1>
        <% if current_user %>
        &nbsp<%= link_to "#{current_user.username.possessive} Starfinder Companion II", root_url%>
        <% else %>
        &nbsp<%= link_to " Starfinder Companion II", root_url%>
        <% end %>
        </h1>
    </div>
</div>

<div class="topnav">
  <% if current_user %>
    <%= link_to "Characters", "#" %>
    <%= link_to "Dice", "#" %>
    <%= link_to "Starships", starships_path %>
    <%= link_to "Sign Out", signout_path, method: :delete %>
  <% else %>
    <%= link_to "Sign In", "/signin" %>
    <%= link_to "Sign Up", new_user_path %>
  <% end %>
</div>

  <body>
    <%= render 'shared/messages' %>
    <%= yield %>
    <div class="footer">
    <p><a href="https://github.com/AndyAtari/StarfinderCompanion2" target="_blank" > Designed by Andy Atari</a></p>
    <p><a href="https://paizo.com/starfinder" target="_blank"> Official Paizo Website</a></p>
    </div>
  </body>
</html>

app/views/shared/_errors.html.erb
<div id="error_explanation">

    <% if obj.errors.any? %>
        <h2><%= pluralize(obj.errors.count, "error") %>
        prevented this from saving:</h2>
        <ul>
        <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
        </ul>
    <% end %> 

</div>

app/views/shared/_messages.html.erb
<div class="row">
 <div class="col-xs-10 col-xs-offset-1">
  <% flash.each do |name, msg| %>
  <div class='alert alert-<%= "#{name}" %>'>
   <a href="#" class="close" data-dismiss="alert">&#215;</a>
   <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
  </div>
  <% end %>
 </div>
</div>

app/views/site/index.html.erb
<% if current_user %> 

<%= react_component("Button") %>

<% else %>

<%= react_component("HomePicture") %>

<% end %>

app/views/starships/index.html.erb
<h1 align="center"><%= current_user.username.possessive %> Starships</h1> 

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>

<%= form_for @user do |f| %> 

    <div class="form">
        <div class="break">
            <%= f.label :username %><br>
            <%= f.text_field :username, placeholder: "Username" %>
        </div>

        <div class="break">
            <%= f.label :email %><br>
            <%= f.text_field :email, placeholder: "Email" %>
        </div>

        <div class="break">
            <%= f.label :password %><br>
            <%= f.password_field :password, placeholder: "Password" %>
        </div>

        <div class="break">
            <%= f.label :password %><br>
            <%= f.password_field :password_confirmation, placeholder: "Confirm Password" %>
        </div>

        <div class="break">
            <%= f.submit %> 
        </div>
    </div>
<% end %> 

app/views/users/edit.html.erb
<h1 align="center">Edit User Account</h1>

<%= render "form" %> 

app/views/users/new.html.erb
<h1 align="center">Signup</h1> 

<%= render "form" %> 